docs: add halo2 page
anonklub/anonklub.github.io pull request #15
Opened 2024-08-19 09:39 UTC by 0xisk

This PR adds docs for Halo2 eth memberhsip circuit.

2024-08-30 13:10 UTC, sripwoud requested changes

2024-08-30 13:10 UTC, sripwoud commented on docs/prove/halo2.md
> +}
can be removed, covered in page added by #17 now right?

2024-08-30 13:10 UTC, sripwoud commented on docs/prove/halo2.md
> +    try {
does not reflect our actual code (no try/catch)

2024-08-30 13:10 UTC, sripwoud commented on docs/prove/halo2.md
> +```js
can be removed too no?
If needed refer to the wasm page

2024-09-21 15:31 UTC, sripwoud requested changes

2024-09-21 15:31 UTC, sripwoud commented on docs/prove/halo2.md
> +[@anonklub/halo2-binary-merkle-tree-worker](https://www.npmjs.com/package/@anonklub/halo2-binary-merkle-tree-worker) and [@anonklub/halo2-eth-membership-worker](https://www.npmjs.com/package/@anonklu
```suggestion
[@anonklub/halo2-binary-merkle-tree-worker](https://www.npmjs.com/package/@anonklub/halo2-binary-merkle-tree-worker) and [@anonklub/halo2-eth-membership-worker](https://www.npmjs.com/package/@anonklub/halo2-eth-membership-worker) are designed to operate on the client side. In the example above, ensure that prepare each worker using `await worker.prepare()`. Please check [`Wasm & Web-Workers`](https://anonklub.github.io/#/prove/wasm) doc for more details.
```

2024-09-21 15:31 UTC, sripwoud commented on docs/prove/halo2.md
> +2. Prepare the list of Ethereum addresses. The Anonklub project can assist in scanning the blockchain to create this list, check out [query docs](https://anonklub.github.io/#/apis?id=query).
that is inaccurate or even incorrect.  
The query API does not scan the blockchain itself. It requests and post processes data from services that serve already scanned/indexed blockchain data.
```suggestion
2. Prepare the list of Ethereum addresses. The Anonklub project can assist in building this list by querying services that serve indexed blockchain data, check out [query docs](https://anonklub.github.io/#/apis?id=query).
```

2024-09-21 15:31 UTC, sripwoud commented on docs/prove/halo2.md
> +  }): Promise<boolean> => {
i think we should provide more information about what `k` is.
If I was a reader new to the project, I wouldn't know what `k` is and what value to choose.
Maybe you should link to the benchmark section here? And make clear that based on the results of your benchmark, you recommend using `k=14` (what the UI does)

2024-09-21 15:31 UTC, sripwoud commented on docs/prove/halo2.md
> +    return await verifyMembership(proof);
this signature is inconsistent with what is described in the TLDR section, 
```ts
const verifyMembership: VerifyMembershipFn = async ({
    membershipProofSerialized,
    k
  }): Promise<boolean>
```
this will confuse readers.
Stick to one.
I suggest in the docs we don't "hide" `k`. So we use everywhere `{ membershipProofSerialized, k }` as params

2024-09-21 15:31 UTC, sripwoud commented on docs/prove/halo2.md
> +## Benchmarks
:+1: 
Great to have thought about adding this section.

2024-09-24 12:58 UTC, 0xisk commented on docs/prove/halo2.md
> +2. Prepare the list of Ethereum addresses. The Anonklub project can assist in scanning the blockchain to create this list, check out [query docs](https://anonklub.github.io/#/apis?id=query).
That is more accurate definition, I updated that in the Spartan page as well.

2024-09-24 13:20 UTC, 0xisk commented on docs/prove/halo2.md
> +  }): Promise<boolean> => {
That is a typo actually, we dont use `k` anymore as params to the worker since it is fixed in the worker page.I added in the Benchmark that we are using KZG on degree of Polynomial of 14 `K`, with a description for both of them.

2024-09-25 07:16 UTC, sripwoud requested changes

2024-09-25 07:16 UTC, sripwoud commented on docs/prove/halo2.md
> +###
```suggestion
```
This messes up the style of the side bar

![image](https://github.com/user-attachments/assets/efea4c19-11e2-4264-b56f-8fdc8e89d119)

2024-09-25 07:16 UTC, sripwoud commented on docs/prove/halo2.md
> +###
Same for the spartan page.
Can you fix it there too?

2024-09-25 07:16 UTC, sripwoud commented on docs/prove/halo2.md
> +import { useStore } from '@/hooks/useStore'
what is `useStore`?
I know what it is, but other devs won't, because this is a custom hook specific to our UI implementation.
Either remove it or link to something that explains what it is.

2024-09-25 07:16 UTC, sripwoud commented on docs/prove/halo2.md
> +import { useHalo2EthMembershipWorker } from '@/hooks/useHalo2EthMembershipWorker'
what is `@/hook`?
I know what this is, but other devs won't.  Because it is a custom alias used by our UI.

2024-09-25 07:16 UTC, sripwoud commented on docs/prove/halo2.md
> +  const { proofRequest } = useStore()
what is `proofRequest`?
Again I know, but it is not described in this page.
Maybe here we can link to https://anonklub.github.io/#/prove/circom?id=create-proof-request

2024-09-25 07:16 UTC, sripwoud commented on docs/prove/halo2.md
> +import { useStore } from '@/hooks/useStore';
same here,
sudden use of custom alias and custom hooks that may confuse devs because they are not documented in this page or anywhere in the docs website.

2024-09-25 07:16 UTC, sripwoud commented on docs/prove/halo2.md
> +    return await verifyMembership(proof);
this is still not matching.
in the TLDR section you are using
```ts
const verifyMembership: VerifyMembershipFn = async ({ membershipProofSerialized }): Promise<boolean>
```

2024-09-30 09:40 UTC, sripwoud requested changes

2024-09-30 09:40 UTC, sripwoud commented on docs/prove/halo2.md
> +```
this is still wrong.
inputs is just `somePositionalArg: Uint8Array` not `{ anonklubProof: Uint8Array }`
so you can't use an interface. You must use a `type` alias. Which is what we do is the UI.

https://github.com/anonklub/anonklub/blob/6884d934f95f2c153bd9531aca36ba7a6e6d4720/pkgs/halo2-eth-membership-worker/src/interface.ts#L22

2024-09-30 09:40 UTC, sripwoud commented on docs/prove/halo2.md
> +//
the import is `@/hooks`
but your comment is about `@hook`
It doesn't match.

In the UI we use neither: we use `@hooks`

2024-09-30 09:40 UTC, sripwoud commented on docs/prove/halo2.md
> +import { useStore } from '@/hooks/useStore';
`@/hooks` or `@hook` or `@hooks`?

2024-09-30 09:40 UTC, sripwoud commented on docs/prove/spartan.md
> +// Hook Path: `@hook` alias points to `src/hooks` for convenient imports.//
`@hooks` or `@/hooks` or `@hook`?

2024-09-30 09:40 UTC, sripwoud commented on docs/prove/spartan.md
> +  //  3. `rawSignature: string` the user signature on the message.
the parameter I read below is `sig`, not `rawSignature`

```
await proveMembership({
      merkleProofBytesSerialized: proofRequest.merkleProof,
      message: proofRequest.message,
      sig: proofRequest.rawSignature as Hex,
    })
  }, [isWorkerReady, proofRequest])
}
```

2024-09-30 09:40 UTC, sripwoud commented on docs/prove/spartan.md
> +// Hook Path: `@hook` alias points to `src/hooks` for convenient imports.//
`@hook` or `@hooks` or `@/hooks`

2024-09-30 13:33 UTC, 0xisk commented on docs/prove/halo2.md
> +//
> In the UI we use neither: we use @hooks

In the UI we use `@/hooks` imports: 
- https://github.com/anonklub/anonklub/blob/6884d934f95f2c153bd9531aca36ba7a6e6d4720/ui/src/hooks/useHalo2EthMembershipWorker.ts#L1

So the typo is missing `/` in the comment

2024-09-30 13:40 UTC, 0xisk commented on docs/prove/spartan.md
> +  //  3. `rawSignature: string` the user signature on the message.
I here took the params that we will find inside the ProofRequest object, because this jsdoc is for describing `ProofRequest` as you mentioned earlier only. But the developer will understand from the code that we use the outputs of this proof request to feed `proveMembership()` params.

2024-10-01 11:36 UTC, merged